export const SPRITE = {
  Capital_1: 'Capital_1',
  Capital_2: 'Capital_2',
  Capital_3: 'Capital_3',
  Capital_4: 'Capital_4',
  APE_APE_CAPITAL: 'APE_APE_CAPITAL',
  APE_ALINE_CAPITAL: 'APE_ALINE_CAPITAL',
  APE_AI_CAPITAL: 'APE_AI_CAPITAL',
  TELEPORT: 'TELEPORT',
  DOGE: 'dogeSheet',
  P1_1: 'P1_1',
  P1_2: 'P1_2',
  P1_3: 'P1_3',
  P2_1: 'P2_1',
  P2_2: 'P2_2',
  P2_3: 'P2_3',
  P3: 'P3',
  P5: 'P5',
  P7_1: 'P7_1',
  P7_2: 'P7_2',
  P8_1: 'P8_1',
  P8_2: 'P8_2',
  EXPLORER: 'explorerSheet',
  TILE: 'tile',
}

export const SPRITE_PLANET = [
  SPRITE.P1_1,
  SPRITE.P1_2,
  SPRITE.P1_3,
  SPRITE.P2_1,
  SPRITE.P2_2,
  SPRITE.P2_3,
  SPRITE.P3,
  SPRITE.P5,
  SPRITE.P7_1,
  //SPRITE.P7_2,
  SPRITE.P8_1,
  //SPRITE.P8_2,
]

export const IMAGE = {
  AI_SHIP: 'AI_SHIP',
  ALIEN_SHIP: 'ALIEN_SHIP',
  APE_SHIP: 'APE_SHIP',
  SELECTED_CURSOR: 'SELECTED_CURSOR',
}
