[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-ed-on-bn254 = { version = "^0.3.0", default-features = false, features = ["r1cs"] }
ark-bn254 = { version = "^0.3.0", default-features = false, features = ["curve"] }
ark-std = { version = "^0.3.0", default-features = false }
ark-relations = { version = "^0.3.0", default-features = false }
ark-crypto-primitives = { version = "^0.3.0", default-features = true, features = ["r1cs"] }
ark-r1cs-std = { version = "^0.3.0", default-features = false }
ark-snark = { version = "^0.3.0", default-features = false }
ark-groth16 = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }

arkworks-native-gadgets = { version = "^1.2.0", default-features = false }
arkworks-r1cs-gadgets = { version = "^1.2.0", default-features = false }
arkworks-utils = { version = "^1.0.1", default-features = false, features = ["poseidon_bn254_x5_4"] }

thiserror = "1.0.35"
hex = "0.4.3"

[dev-dependencies]
ark-groth16 = { version = "^0.3.0", default-features = false, features = ["print-trace"] }
